### ISSUE TITLE
npm run build fails to compile

### ISSUE THREAD

**Issue by AdrianScott** [decent-bet/dbet-wallet#2]
i'm guessing this is a node/npm version issue vs. react-box requirements, but don't see version requirements listed in react-box docs... i can look at this a little more tomorrow... this is on my fedora laptop...

$ npm run build

> react-box@0.1.0 build /home/adrian/dbet/dbet-wallet
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

static/js/main.dbf7e03f.js from UglifyJs
SyntaxError: Unexpected token: name (SHA3) [./~/ethereum-address/index.js:3,0]

npm ERR! Linux 4.5.5-300.fc24.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-box@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1

$ npm bugs react-box
$

**Comment by decent-dev** [comment]
Closing since it works now
